### ISSUE TITLE
cannot found JanusGraph_Cluster_metrics 

### ISSUE THREAD

**Issue by sinnergarden** [gguttikonda/janusgraph-prometheus#2]
After apply your janusgraph-dashboard.json, I succeed produce similar dashboard.

However, I found that the dashboard cannot show metrics start with `JanusGraph_Cluster_metrics`. (4th to 9th panel) JMX exporter also doesn't give this kind of info.

Is there any other settings we need to do to get that metrics ? 

Thanks.

**Comment by gguttikonda** [comment]
@sinnergarden : You may want to check `gremlin-server.yaml` with below settings.

`metrics: {
  consoleReporter: {enabled: true, interval: 180000},
  jmxReporter: {enabled: true},
  slf4jReporter: {enabled: true, interval: 180000},
  gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
  graphiteReporter: {enabled: false, interval: 180000}}
`

**Comment by sinnergarden** [comment]
@gguttikonda Thanks for your kind reply. 

Here is our settings, except for `consoleReporter` and `csvReporter`, which I think do not related to the issue, others are just the same. 

```
metrics: {
  consoleReporter: {enabled: false, interval: 180000},
  csvReporter: {enabled: true, interval: 180000, fileName: /tmp/gremlin-server-metrics.csv},
  jmxReporter: {enabled: true},
  slf4jReporter: {enabled: true, interval: 180000},
  gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
  graphiteReporter: {enabled: false, interval: 180000}}
```

Also, in official doc of Tinkerpop, http://tinkerpop.apache.org/docs/current/reference/#metrics
It only provides metrics start with `org.apache.tinkerpop.gremlin.server.GremlinServer`, which we can get and show it on Grafana. 

But the metrics start with `JanusGraph_Cluster_metrics ` in your `janusgraph-dashboard.json`, can not be find.

**Comment by gguttikonda** [comment]
Hi @sinnergarden , I dont think there are any other settings I have updated to get them. That said, I am using JanusGraph 0.4. Also, can you please verify if you happen to have `metrics.prefix` property ? JanusGraph documentation : https://docs.janusgraph.org/advanced-topics/monitoring/

**Comment by sinnergarden** [comment]
@gguttikonda I think I found the reason.

I only set the metrics report in gremlin server. but haven't set that in graph property files. 
Thanks for your help
